### ISSUE TITLE
버튼 이름을 어떻게 바꾸는 것이 깔끔할까요

### ISSUE THREAD

**Issue by 1111792** [jwony/swengineering#5]
btnAdd같이 btn을 button으로 그냥 길게 풀어 쓸까요?
좋은 방법이 있으면 공유합시다.

**Comment by jwony** [comment]
저는 다 button으로 풀어썼습니다! 그게 안 헷갈릴거 같아서요

**Comment by 1111792** [comment]
btn은 button으로 풀어 쓰도록 합시다.
